-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(d9660a)",
			inactive_border = "rgb(767ba6)",
		},
	},
	group = {
		col = {
			border_active = "rgb(d9660a)",
			border_inactive = "rgb(767ba6)",
			border_locked_active = "rgb(ff6e6e)",
			border_locked_inactive = "rgb(767ba6)",
		},
		groupbar = {
			col = {
				active = "rgb(d9660a)",
				inactive = "rgb(767ba6)",
				locked_active = "rgb(ff6e6e)",
				locked_inactive = "rgb(767ba6)",
			},
		},
	},
})
