-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "capitaine-cursors-light")
hl.env("XCURSOR_THEME", "capitaine-cursors-light")
hl.env("HYPRCURSOR_SIZE", "18")
hl.env("XCURSOR_SIZE", "18")

hl.config({
	cursor = {
		hide_on_key_press = true,
		hide_on_touch = true,
	},
})
