-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "1366x768@60.003", position = "0x0", scale = 1, vrr = 0, bitdepth = 10, cm = "edid" })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.000", position = "0x0", scale = 1, vrr = 0, mirror = "eDP-1", bitdepth = 10, cm = "dp3" })
